name: "Tests" # The name of the workflow

on:
    pull_request: # Trigger on PRs
    push: # Trigger on pushes

jobs:
    run-tests:
        name: Run Tests
        runs-on: ubuntu-latest # Use latest Ubuntu runner
        steps:
            - uses: actions/checkout@v2 # Check out your repo
            - name: Install modules
              working-directory: ./ # Path where package.json is
              run: npm ci # Clean install dependencies
            - name: Run Tests
              working-directory: ./
              run: npm run test # Run Jest tests
